In [7]:
## transpose a matrtix
m = [[1,2],[3,4],[5,6]]
for row in m:
    print (row)
rez = [[m[i][j] for j in range(len(m))] for i in range(len(m[0]))]
print('\n')
for row in rez:
    print('row')


[1, 2]
[3, 4]
[5, 6]


IndexError: list index out of range

In [17]:
print("using zip")
matrix = [(1,2,3),(4,5,6),(7,8,9),(2,1,3)]
for row in matrix:
    print(row)
    
t_matrix = zip(*matrix)
for row in t_matrix:
    print(row)

using zip
(1, 2, 3)
(4, 5, 6)
(7, 8, 9)
(2, 1, 3)
(1, 4, 7, 2)
(2, 5, 8, 1)
(3, 6, 9, 3)


In [22]:
import numpy 
matrix = [(1,2,3),(4,5,6),(7,8,9),(2,1,3)]
print(matrix)

print(numpy.transpose(matrix))


[(1, 2, 3), (4, 5, 6), (7, 8, 9), (2, 1, 3)]
[[1 4 7 2]
 [2 5 8 1]
 [3 6 9 3]]


In [24]:
# global variable and local variable
a=1
#use global variable
def f():
    print("f a is", a)
    
# redefine a as locaal variable
def g():
    a=2
    print("g a is", a)

def h():
    global a
    a=3
    print("h a is", a)
    
print("global", a)
f()
print("global", a)
g()
print("global", a)
h() 
    
    
    


global 1
f a is 1
global 1
g a is 2
global 1
h a is 3


In [28]:
#partial fuction calling a fuction 
from functools import partial
def f(a,s,d,x):
   return(a*1+s*1+d*1+x*1)
g= partial(f,2,3,4)
print(g(6))



15


In [40]:
#packing and unpacking of arguments
def f(a,b,c,d):
    print(a,b,c,d)
    
mylist=[1,2,3,4] #list is pack we have to un pack it by using *

f(*mylist)

#packing and unpacking
def fuc1(a,b,c):
    print(a,b,c)
    
def func2(*args): #packing arguments passed in fuc2 put them in tuple
    sum =0
    for i in range(0,len(args)):
        sum = sum + args[i]
    return sum

s= func2(1,2,3,4,5)
print(s)
print(func2(9,7,6,8))

#packing dictionary **

def f(**kwargs):
    print(type(kwargs))#kwargs is a dict
    
    for key in kwargs:
        print(key,kwargs[key])

f(name="aditya", id="123")



1 2 3 4
15
30
<class 'dict'>
name aditya
id 123


In [42]:
#encoding and decoding (byte object(machine readable and string object(human readble)))
#string encoding
a="simple string object"

c = b'simple string object' #byte object coversion because of b'
 
d=a.encode("ASCII") #encoding the string to byte code

if (d==c):
    print("succcessful")
else:
    print("unsucessful")







succcessful
